fixed __version__ + fixed bug with maturin pipeline due to change in PEP + add wheels for python 3.10,11

diff --git a/.github/workflows/release-python.yml b/.github/workflows/release-python.yml
--- a/.github/workflows/release-python.yml
+++ b/.github/workflows/release-python.yml
@@ -33,7 +33,7 @@ jobs:
       - name: Build with maturin
         run: |
           python -m pip install --upgrade pip
-          pip install maturin==1.1.0
+          pip install --upgrade maturin==1.8.7
           maturin sdist --manifest-path Cargo.toml --out dist
           
 
@@ -65,8 +65,8 @@ jobs:
       matrix:
         os: [ubuntu-latest, macos-14, macos-latest, windows-latest]
         # os: [macos-14]
-        python-version: ["3.9"] # , "3.10"
-        # python-version: ["3.10"]
+        python-version: ["3.9", "3.10", "3.11"] # , "3.10"
+        
         architecture: [x86_64, aarch64]  # Explicitly define architectures
         # architecture: [aarch64]  # Explicitly define architectures
         exclude:
@@ -98,7 +98,7 @@ jobs:
       - name: Create source distribution
         run: |
           python -m pip install --upgrade pip
-          pip install maturin==1.1.0
+          pip install --upgrade maturin==1.8.7
           maturin build --manifest-path Cargo.toml --profile dist-release --out target/wheels
           
 
@@ -161,8 +161,9 @@ jobs:
           TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
         run: |
           ls -R artifacts/
+          pip install --upgrade --force-reinstall twine
           twine check artifacts/**/*.tar.gz 
-          twine upload artifacts/**/*.tar.gz 
+          twine upload artifacts/**/*.tar.gz  || echo "Failed to upload artifacts/**/*.tar.gz "
           twine check artifacts/**/*.whl
           for file in artifacts/**/*.whl; do
             if [[ -f "$file" ]]; then
