feat : upgraded pyo3 and removed deprecated code incompatible with pyo3 newest version

diff --git a/.github/workflows/release-python.yml b/.github/workflows/release-python.yml
--- a/.github/workflows/release-python.yml
+++ b/.github/workflows/release-python.yml
@@ -164,4 +164,10 @@ jobs:
           twine check artifacts/**/*.tar.gz 
           twine upload artifacts/**/*.tar.gz 
           twine check artifacts/**/*.whl
-          twine upload artifacts/**/*.whl
+          for file in artifacts/**/*.whl; do
+            if [[ -f "$file" ]]; then
+              echo "Uploading $file..."
+              twine upload "$file" || echo "Failed to upload $file"
+            fi
+          done
+          # twine upload artifacts/**/*.whl
