fix: update cargo.toml align versioning for github workflow

diff --git a/.github/workflows/release-python.yml b/.github/workflows/release-python.yml
--- a/.github/workflows/release-python.yml
+++ b/.github/workflows/release-python.yml
@@ -22,18 +22,33 @@ jobs:
         with:
           python-version: 3.9
 
-      - name: Create source distribution
-        uses: PyO3/maturin-action@v1
-        with:
-          command: sdist
-          args: >
-            --manifest-path Cargo.toml
-            --out dist
+      # - name: Create source distribution
+      #   uses: PyO3/maturin-action@v1
+      #   with:
+      #     command: sdist
+      #     args: >
+      #       --manifest-path Cargo.toml
+      #       --out dist
 
+      - name: Build with maturin
+        run: |
+          python -m pip install --upgrade pip
+          pip install maturin==1.1.0
+          maturin sdist --manifest-path Cargo.toml --out dist
+          
+
+      - name: Inspect Source Distribution
+        run: |
+          for file in dist/*.tar.gz; do
+            echo "Inspecting $file"
+            tar --wildcards -tzf "$file" | grep PKG-INFO || echo "PKG-INFO not found"
+            tar --wildcards -xOf "$file" */PKG-INFO || echo "Unable to read PKG-INFO"
+          done
+  
       - name: Test sdist
         run: |
           python -m pip install --upgrade pip
-          pip install twine
+          pip install --upgrade --force-reinstall twine
           twine check dist/*.tar.gz
           pip install --force-reinstall --verbose dist/*.tar.gz
           python -c 'from polodb import PoloDB'
@@ -52,13 +67,13 @@ jobs:
         # os: [macos-14]
         python-version: ["3.9"] # , "3.10"
         # python-version: ["3.10"]
-        architecture: [x86_64, arm64]  # Explicitly define architectures
+        architecture: [x86_64, aarch64]  # Explicitly define architectures
         # architecture: [aarch64]  # Explicitly define architectures
         exclude:
           - os: windows-latest
-            architecture: arm64
+            architecture: aarch64
           - os: macos-latest
-            architecture: arm64   # macOS 13 on GitHub Actions is only x86_64 (Intel)
+            architecture: aarch64   # macOS 13 on GitHub Actions is only x86_64 (Intel)
           - os: macos-14
             architecture: x86_64
   
@@ -71,14 +86,22 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
+      # - name: Create source distribution
+      #   uses: PyO3/maturin-action@v1
+      #   with:
+      #     command: build
+      #     args: >
+      #       --manifest-path Cargo.toml
+      #       --profile dist-release
+      #       --out target/wheels
+
       - name: Create source distribution
-        uses: PyO3/maturin-action@v1
-        with:
-          command: build
-          args: >
-            --manifest-path Cargo.toml
-            --profile dist-release
-            --out target/wheels
+        run: |
+          python -m pip install --upgrade pip
+          pip install maturin==1.1.0
+          maturin build --manifest-path Cargo.toml --profile dist-release --out target/wheels
+          
+
 
       - name: Extract Version from pyproject.toml
         id: get_version
